### ISSUE TITLE
Program appears to freeze

### ISSUE THREAD

**Issue by nanthony21** [Longoon12000/DownloadPavlovMapsFromModIo#8]
This tool worked great for me the first few times I used it, but now it is very slow. It sometimes seems to freeze entirely, this can happen in the middle of a download or before the list of maps has even been shown. I'm guessing that this is some issue with the mod.io API requests but am not sure. Is there any sort of debug log to help me figure out what the problem is?

**Comment by RainOrigami** [comment]
Hi @nanthony21 

A similar issue to yours was reported by kioley on reddit:

https://old.reddit.com/r/PavlovGame/comments/17fss3i/modio_not_working/
https://old.reddit.com/r/PavlovGame/comments/17ka91m/can_somebody_upload_their_mod_folder/

Since the tool only does a very simple GET request and downloads the data from mod.io (https://github.com/RainOrigami/DownloadPavlovMapsFromModIo/blob/main/Program.cs#L140C73-L140C73) there is not a lot that can go wrong here. Any error would be printed to the console, so there no debug log other than what is printed. The progress bar itself is the "debug log" in the sense that it provides insight into how many bytes have been received, and there isn't really anything else happening here that can be logged.

I assume the problem is that it downloads a map and then stops at some percentage?

Can you provide:
- Screenshot
- Which map(s) is/are affected
- What percentage they stop at
- Is this consistent? (always stops at around xx% or it's always this one map)

Can you also do a speed test on https://speedtest.net/ to see if it completes or if it has a similar issue of only downloading some data and then stalling?

I would assume that there is some issue between mod.io and your PC that causes this. If this is the case and it is not solvable I could try and implement a more detailed download process that detects stalls and re-tries or resumes the download, if mod.io supports resume, but that would only be a workaround for some underlying issue that should be solved instead.

It would be really nice to find out what the issue is but since I can not reproduce this at all, it's hard to pinpoint the cause.

**Comment by RainOrigami** [comment]
One more thing that I want to exclude as a cause is, windows command line stops the program if you click and select something. As soon as you click into the command line window it will select a single character (displayed as a █) and stop execution. To resume, simply right click so that the █ disappears.

Can you confirm that the issue is not that you accidentally clicked into the window and caused the program to pause execution?

https://github.com/RainOrigami/DownloadPavlovMapsFromModIo/assets/51454971/a06e2527-ed15-4328-ae64-a45492b9980b

**Comment by nanthony21** [comment]
>  As soon as you click into the command line window it will select a single character (displayed as a █) and stop execution.  

I'm familiar with this quirk of the command line and I'm sure that this hasn't been the case when I've run into this issue.


 > Can you provide:
 - Screenshot: I wasn't able to reproduce the issue just now, but the output doesn't look any different than when things run normally, it just takes a long time to proceed through each item.
 - Which map(s) is/are affected: I haven't noticed any patterns as far as where in the download this issue will occur. Often times the problem is before any downloading has actually started. For example, it will take ~10 minutes just to go through the first few lines. For example, excluding "Pavlov VR Mod Downloader version 8", each of these first lines will take a few minutes before they appear: 
![image](https://github.com/RainOrigami/DownloadPavlovMapsFromModIo/assets/8433487/c878134f-13be-4ade-ad14-343daf98cdf0)

 - Is this consistent? (always stops at around xx% or it's always this one map): This doesn't appear to be consistent at all. However, when the problem is happening then there is nothing to fix it except for wait. For example, re-running the program or restarting the computer isn't going to fix the issue. I think that it must just be some intermittent issue with mod.io but I thought that if there was a way to view the timestamps for each GET request then there might be some useful information.

**Comment by RainOrigami** [comment]
Thank you for your response!

The first line, version 8, is printed once the program starts with no delay.
Afterwards the line "Found xx subscribed Pavlov VR mods" requires to fetch your subscribed mods from mod.io so it will do an api request and wait for a response. Usually this should be blazingly fast, like <1s.

I can only think that maybe I have introduced a bug in v8 because the process of receiving your subscribed mods is executed multiple times if you have more than 100 subscribed mods. It will loop until all mods have been received. I hope that mod.io doesn't "hide" a mod from this list, causing it to keep querying the api until it has all mods.

To test this, you would have to do the api request using something like postman

`GET https://api.mod.io/v1/me/subscribed?game_id=3959&_limit=100&_offset=0`  
Header `Authorization` value `Bearer yourverylongtokengoeshere`

I also know that mod.io uses cloudflare and a lot of cloudflare enabled websites have the problem that initial requests take up to 2 minutes, then time out, and then subsequent requests work perfectly fine. Maybe this is related? I have this all the time that a website just won't load for minutes on end, no matter how many times I make the request. Only after failing once after a few minutes will it then load the page and work.

I am not sure if there even is a solution. We could only send a mail to mod.io describing the issue however without a full network analysis from when this happens, I don't think they will be able to do anything about it either.

My best guess is that it's either cloudflare or mod.io.

For v9 I will add a `-v` startup parameter that will add a *lot* of logging so that it is possible to pinpoint the issue to networking or if it is indeed a bug in my v8 code.
